#!/usr/bin/env python
"""Subset Font Awesome + Academicons to ONLY the glyphs this site uses, and emit a
single self-hosted assets/icons.css (+ assets/fonts/*.woff2). Replaces ~420 KB of
CDN icon CSS/fonts with ~15-20 KB and drops two third-party CDN dependencies.

This is a MANUAL, local build step — it needs `fonttools` + `brotli` (pip) and the
source fonts/CSS cached under scripts/.icon-cache/. It is deliberately NOT wired into
the Quarto pre-render, so CI stays dependency-free and offline; the outputs are
committed as static assets. Re-run it (and re-render) whenever you add a new icon.

    pip install fonttools brotli
    # (cache the source fa.css/ai.css + fa-solid-900.woff2 / fa-brands-400.woff2 /
    #  academicons.ttf under scripts/.icon-cache/ — see the URLs in git history)
    python scripts/build-icons.py

The icon lists below are the UNION of every fa-*/ai-* class across the rendered HTML
AND the JS that injects icons at runtime (site.js/paper.js: theme toggle, badges,
journey map, CV timeline, copy button). Missing one here = a broken icon on the site.
"""
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CACHE = os.path.join(HERE, '.icon-cache')
FONTS_OUT = os.path.join(ROOT, 'assets', 'fonts')
CSS_OUT = os.path.join(ROOT, 'assets', 'icons.css')

# --- the exact icons the site uses (union of HTML + JS-injected) -----------------
SOLID = ['arrow-up-right-from-square', 'bars', 'briefcase', 'circle-check', 'code',
         'copy', 'envelope', 'expand', 'file-arrow-down', 'file-pdf', 'flask', 'gear',
         'globe', 'graduation-cap', 'hourglass-half', 'location-dot', 'microphone-lines',
         'moon', 'people-group', 'phone', 'quote-right', 'star', 'sun', 'thumbtack',
         'up-right-from-square', 'xmark']
BRANDS = ['bluesky', 'github', 'r-project', 'x-twitter']
AI = ['google-scholar', 'open-access', 'open-data', 'open-materials', 'orcid', 'osf',
      'preregistered', 'psyarxiv', 'researchgate', 'zotero']


def codepoints(css_path, prefix, names):
    css = open(css_path, encoding='utf-8').read()
    out, missing = {}, []
    for n in names:
        # Allow alias selectors sharing the rule, e.g. ".fa-bars:before,.fa-navicon:before{content:...}"
        m = re.search(r'\.' + re.escape(prefix + '-' + n) + r'::?before[^{}]*\{[^}]*content:\s*"\\([0-9a-fA-F]+)"', css)
        if m:
            out[n] = int(m.group(1), 16)
        else:
            missing.append(prefix + '-' + n)
    if missing:
        sys.exit('MISSING codepoints (icon renamed/removed upstream?): ' + ', '.join(missing))
    return out


def subset(src, unicodes, out):
    from fontTools import subset as ss
    opts = ss.Options()
    opts.flavor = 'woff2'
    opts.desubroutinize = True
    opts.layout_features = []          # icon fonts need no OpenType layout
    opts.name_IDs = []
    opts.notdef_outline = True
    sub = ss.Subsetter(options=opts)
    font = ss.load_font(src, opts)
    sub.populate(unicodes=list(unicodes.values()))
    sub.subset(font)
    ss.save_font(font, out, opts)
    return os.path.getsize(out)


def main():
    os.makedirs(FONTS_OUT, exist_ok=True)
    solid = codepoints(os.path.join(CACHE, 'fa.css'), 'fa', SOLID)
    brands = codepoints(os.path.join(CACHE, 'fa.css'), 'fa', BRANDS)
    ai = codepoints(os.path.join(CACHE, 'ai.css'), 'ai', AI)

    s1 = subset(os.path.join(CACHE, 'fa-solid-900.woff2'), solid, os.path.join(FONTS_OUT, 'fa-solid-900.woff2'))
    s2 = subset(os.path.join(CACHE, 'fa-brands-400.woff2'), brands, os.path.join(FONTS_OUT, 'fa-brands-400.woff2'))
    s3 = subset(os.path.join(CACHE, 'academicons.ttf'), ai, os.path.join(FONTS_OUT, 'academicons.woff2'))

    def rules(cps, prefix):
        return ''.join('.%s-%s::before{content:"\\%x"}\n' % (prefix, n, c) for n, c in sorted(cps.items()))

    css = (
        '/* GENERATED by scripts/build-icons.py — subset icon fonts (FA + Academicons).\n'
        '   Only the glyphs the site uses. Regenerate if you add an icon. Do not edit. */\n'
        '@font-face{font-family:"Font Awesome 6 Free";font-style:normal;font-weight:900;font-display:block;src:url(fonts/fa-solid-900.woff2) format("woff2")}\n'
        '@font-face{font-family:"Font Awesome 6 Brands";font-style:normal;font-weight:400;font-display:block;src:url(fonts/fa-brands-400.woff2) format("woff2")}\n'
        '@font-face{font-family:"Academicons";font-style:normal;font-weight:normal;font-display:block;src:url(fonts/academicons.woff2) format("woff2")}\n'
        '.fa,.fas,.fa-solid,.fab,.fa-brands{-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;display:inline-block;font-style:normal;font-variant:normal;line-height:1;text-rendering:auto}\n'
        '.fa-solid,.fas{font-family:"Font Awesome 6 Free";font-weight:900}\n'
        '.fa-brands,.fab{font-family:"Font Awesome 6 Brands";font-weight:400}\n'
        '.ai{display:inline-block;font-family:"Academicons";font-style:normal;font-weight:normal;line-height:1;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}\n'
        + rules(solid, 'fa') + rules(brands, 'fa') + rules(ai, 'ai')
    )
    open(CSS_OUT, 'w', encoding='utf-8', newline='\n').write(css)

    total = (s1 + s2 + s3) / 1024
    print('subset fonts: fa-solid %.1fKB (%d), fa-brands %.1fKB (%d), academicons %.1fKB (%d)'
          % (s1/1024, len(solid), s2/1024, len(brands), s3/1024, len(ai)))
    print('total fonts: %.1f KB + icons.css %.1f KB -> assets/fonts/ + assets/icons.css' % (total, len(css)/1024))


if __name__ == '__main__':
    main()
