#!/usr/bin/env node
/* Geocode the cities used in assets/data/journey.js → assets/data/city-coords.js
 *
 * You only ever write `city` + `country` in journey.js; this fills in the
 * coordinates automatically from the bundled GeoNames "cities15000" dataset
 * (cities ≥15,000 inhabitants), matched by name + country and disambiguated by
 * population. Run it after adding/renaming a city:
 *
 *     node scripts/geocode-cities.mjs
 *
 * It also runs automatically before every `quarto render` (see _quarto.yml
 * `pre-render`), so coordinates stay in sync with no manual step.
 *
 * For the rare place GeoNames can't resolve (a tiny village, an ambiguous
 * name), add an entry to OVERRIDES below — it always wins.
 */
import fs from 'node:fs';
import zlib from 'node:zlib';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const JOURNEY = path.join(root, 'assets/data/journey.js');
const OUT = path.join(root, 'assets/data/city-coords.js');
const DATASET = path.join(here, 'data/cities15000.txt.gz');

// Manual overrides — "City|Country": [lon, lat]. Wins over geocoding.
const OVERRIDES = {
  // 'Some Village|Spain': [-3.12, 40.55],
};

// Country name → ISO-3166 alpha-2 (extend as needed).
const ISO = {
  Spain: 'ES', Portugal: 'PT', France: 'FR', Italy: 'IT', Germany: 'DE',
  Netherlands: 'NL', Belgium: 'BE', Switzerland: 'CH', Austria: 'AT',
  'United Kingdom': 'GB', UK: 'GB', Ireland: 'IE', Greece: 'GR', Poland: 'PL',
  Sweden: 'SE', Norway: 'NO', Denmark: 'DK', Finland: 'FI', Czechia: 'CZ',
  'Czech Republic': 'CZ', Hungary: 'HU', Romania: 'RO', Croatia: 'HR',
  'United States': 'US', USA: 'US', Canada: 'CA', Mexico: 'MX', Brazil: 'BR',
  Argentina: 'AR', Chile: 'CL', Japan: 'JP', China: 'CN', 'South Korea': 'KR',
  India: 'IN', Australia: 'AU', 'New Zealand': 'NZ', Israel: 'IL', Turkey: 'TR',
};

const norm = (s) => s.normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase().trim();

function readJourney() {
  const win = {};
  new Function('window', fs.readFileSync(JOURNEY, 'utf8'))(win);
  const list = win.FGF_JOURNEY || [];
  const seen = new Map();
  for (const j of list) {
    if (!j.city || !j.country) continue;
    const key = j.city + '|' + j.country;
    if (!seen.has(key)) seen.set(key, { city: j.city, country: j.country });
  }
  return [...seen.values()];
}

let _rows = null;
function rows() {
  if (_rows) return _rows;
  const txt = zlib.gunzipSync(fs.readFileSync(DATASET)).toString('utf8');
  _rows = txt.split('\n').filter(Boolean).map((l) => l.split('\t'));
  return _rows;
}

// GeoNames columns: 1 name, 2 asciiname, 3 alternatenames, 4 lat, 5 lon, 8 cc, 14 population
function geocode(city, country) {
  const cc = ISO[country];
  if (!cc) return { error: `unknown country "${country}" (add it to ISO map)` };
  const target = norm(city);
  let best = null;
  for (const r of rows()) {
    if (r[8] !== cc) continue;
    const names = [r[1], r[2], ...(r[3] ? r[3].split(',') : [])].map(norm);
    if (!names.includes(target)) continue;
    const pop = +r[14] || 0;
    if (!best || pop > best.pop) best = { lon: +r[5], lat: +r[4], pop, name: r[1] };
  }
  return best ? { lon: best.lon, lat: best.lat, name: best.name } : { error: 'not found in GeoNames' };
}

function main() {
  const cities = readJourney();
  const coords = {};
  const problems = [];
  for (const { city, country } of cities.sort((a, b) => (a.city + a.country).localeCompare(b.city + b.country))) {
    const key = city + '|' + country;
    if (OVERRIDES[key]) { coords[key] = OVERRIDES[key].map((n) => +n.toFixed(4)); continue; }
    const g = geocode(city, country);
    if (g.error) { problems.push(`  ✗ ${key} — ${g.error}`); continue; }
    coords[key] = [+g.lon.toFixed(4), +g.lat.toFixed(4)];
  }

  const body = Object.keys(coords).sort()
    .map((k) => `  ${JSON.stringify(k)}: [${coords[k][0]}, ${coords[k][1]}],`).join('\n');
  const out = `/* AUTO-GENERATED by scripts/geocode-cities.mjs — do not edit by hand.\n` +
    ` * City coordinates resolved from GeoNames by name + country.\n` +
    ` * Add a city by name in journey.js, then re-run the script (or just render). */\n` +
    `window.FGF_CITY_COORDS = {\n${body}\n};\n`;
  fs.writeFileSync(OUT, out);

  console.log(`geocoded ${Object.keys(coords).length}/${cities.length} cities → ${path.relative(root, OUT)}`);
  if (problems.length) {
    console.error('\nUNRESOLVED cities (add to OVERRIDES in scripts/geocode-cities.mjs):');
    console.error(problems.join('\n'));
    process.exitCode = 1;
  }
}

main();
