// =============================================================================
// fgf-cv — a Quarto Typst format that carries the franfrutos.github.io
// design language (IBM Plex Mono, coral accent, dot-divider motif, hairline
// section rules, Academicons + Font Awesome icons) onto a light, printable page.
//
// Palette mirrors the site's *light* design tokens (theme.scss):
//   ink #1a1d24 · ink2 #454b59 · ink3 #878d9b · line #e1e3e9 · accent #e8421d
// The body of the document is generated by scripts/build-cv.mjs, which calls
// the helper functions defined below.
// =============================================================================

// Light by default; a dark variant is produced by recompiling with
// `--input fgfdark=1` (see _quarto.yml post-render). Palettes mirror the
// website's light and `html.fgf-dark` design tokens (theme.scss).
#let _dark  = sys.inputs.at("fgfdark", default: "0") == "1"
#let ink    = if _dark { rgb("#e9ebef") } else { rgb("#1a1d24") }  // primary text
#let ink2   = if _dark { rgb("#aab0bd") } else { rgb("#454b59") }  // secondary
#let ink3   = if _dark { rgb("#6c7382") } else { rgb("#878d9b") }  // muted meta
#let hair   = if _dark { rgb("#2b2f3a") } else { rgb("#e1e3e9") }  // hairlines
#let accent = if _dark { rgb("#ff5a3c") } else { rgb("#e8421d") }  // coral
#let paper  = if _dark { rgb("#1b1e26") } else { white }           // page fill
#let chip   = if _dark { rgb("#2a2018") } else { accent.lighten(91%) }  // badge fill
#let chipln = if _dark { rgb("#5a3a30") } else { accent.lighten(55%) }  // badge stroke
#let mono   = "IBM Plex Mono"

// --- Icon fonts (bundled in fonts/). Glyph codepoints taken from the same
//     Font Awesome 6.6 / Academicons 1.9.4 the website loads. -----------------
#let FA_SOLID  = "Font Awesome 6 Free Solid"
#let FA_BRANDS = "Font Awesome 6 Brands"
#let AI        = "Academicons"
#let _ICONS = (
  phone:   (FA_SOLID,  "\u{f095}"),
  email:   (FA_SOLID,  "\u{f0e0}"),
  web:     (FA_SOLID,  "\u{f0ac}"),
  github:  (FA_BRANDS, "\u{f09b}"),
  bluesky: (FA_BRANDS, "\u{e671}"),
  scholar: (AI,        "\u{e9d4}"),
  orcid:   (AI,        "\u{e9d9}"),
  osf:     (AI,        "\u{e9ef}"),
)
#let icon(name, size: 9.5pt, fill: accent) = {
  let s = _ICONS.at(name, default: none)
  if s != none { text(font: s.at(0), size: size, fill: fill, baseline: 0.6pt)[#s.at(1)] }
}
// Open-science practice glyphs as (font, codepoint). Most are Academicons;
// "open code" uses Font Awesome's </> (fa-code), matching the website.
#let _OSF = (
  prereg:    (AI,       "\u{e906}"),  // ai-preregistered
  materials: (AI,       "\u{e968}"),  // ai-open-materials
  data:      (AI,       "\u{e966}"),  // ai-open-data
  code:      (FA_SOLID, "\u{f121}"),  // fa-code </>
  oa:        (AI,       "\u{e939}"),  // ai-open-access
  preprint:  (AI,       "\u{e90e}"),  // ai-psyarxiv — a preprint shows its PsyArXiv glyph in the OA slot
  postprint: (AI,       "\u{e90e}"),  // ai-psyarxiv — shown in the OA slot when not OA but a postprint is shared
  production:(FA_SOLID, "\u{f013}"),  // fa-gear — accepted/in press, final access status still pending
)

// --- Section header: coral tick + uppercase muted label + hairline rule.
//     `sticky` keeps the header on the same page as the entry that follows it. -
#let cvsection(title) = block(above: 27pt, below: 12pt, breakable: false, sticky: true, width: 100%, {
  grid(
    columns: (auto, 1fr),
    column-gutter: 12pt,
    align: horizon,
    {
      box(width: 22pt, height: 2pt, fill: accent, baseline: -2.5pt)
      h(9pt)
      text(font: mono, size: 9.3pt, weight: "semibold", tracking: 1.4pt, fill: ink3)[#upper(title)]
    },
    line(length: 100%, stroke: 0.6pt + hair),
  )
})

// --- A two-column entry: title / right-meta, org / dates, then body. --------
#let entry(title: none, right: none, org: none, dates: none, body: none) = {
  block(above: 16.5pt, below: 0pt, breakable: false, width: 100%, {
    if title != none or right != none {
      grid(
        columns: (1fr, auto),
        column-gutter: 16pt,
        align: (start + bottom, end + bottom),
        text(font: mono, size: 10.7pt, weight: "semibold", fill: ink)[#title],
        text(font: mono, size: 9.1pt, style: "italic", fill: ink3)[#right],
      )
    }
    if org != none or dates != none {
      v(3pt)
      grid(
        columns: (1fr, auto),
        column-gutter: 16pt,
        align: (start + bottom, end + bottom),
        text(font: mono, size: 8.2pt, weight: "medium", tracking: 0.7pt, fill: ink3)[#upper(org)],
        text(font: mono, size: 9.2pt, style: "italic", fill: ink3)[#dates],
      )
    }
    if body != none {
      v(7pt)
      set text(font: mono, size: 9.3pt, fill: ink2)
      set par(leading: 8pt, justify: false)
      body
    }
  })
}

// --- Labeled inline field used inside entry bodies (Thesis:, Supervisor:…). -
#let kv(label, value) = block(above: 6pt, below: 0pt, {
  text(font: mono, size: 8.5pt, weight: "semibold", fill: ink)[#label:]
  h(5pt)
  text(font: mono, size: 9.3pt, fill: ink2)[#value]
})

// --- A small rounded "open science" badge (Academicons glyph), as a soft
//     coral chip so the open-science practices read at a glance. -------------
#let osfbadge(key, on: true) = {
  let g = _OSF.at(key)
  box(
    inset: (x: 4pt, y: 3pt),
    radius: 3.5pt,
    fill: if on { chip } else { none },
    stroke: 0.5pt + if on { chipln } else { hair },
    baseline: 3.6pt,
    text(font: g.at(0), size: 9.5pt, fill: if on { accent } else { ink3 })[#g.at(1)],
  )
}

// --- A right-aligned label + value row (Methods & Technical Expertise). -----
#let methodrow(label, value) = block(above: 7.5pt, below: 0pt, {
  grid(
    columns: (4.6cm, 1fr),
    column-gutter: 14pt,
    align: (end + top, start + top),
    text(font: mono, size: 9.3pt, weight: "semibold", fill: ink)[#label],
    {
      set par(leading: 7.6pt, justify: false)
      text(font: mono, size: 9.3pt, fill: ink2)[#value]
    },
  )
})

// --- A publication / talk list item: coral bullet + body + optional badges. --
#let pubitem(body, badges: ()) = block(above: 11pt, below: 0pt, breakable: false, width: 100%, {
  grid(
    columns: (14pt, 1fr),
    column-gutter: 4pt,
    align: (left + top, left + top),
    { v(5pt); box(width: 7pt, height: 1.8pt, fill: accent, radius: 0.9pt) },
    {
      set text(font: mono, size: 9.3pt, fill: ink2)
      set par(leading: 7.9pt, justify: false)
      body
      if badges.len() > 0 {
        v(4pt)
        box(stack(dir: ltr, spacing: 5pt, ..badges.map(b => osfbadge(b.at(0), on: b.at(1)))))
      }
    },
  )
})

// --- A small uppercase subgroup label (e.g. ORAL PRESENTATIONS). ------------
#let subhead(title) = block(above: 15pt, below: 4pt, sticky: true, {
  text(font: mono, size: 8.2pt, weight: "semibold", tracking: 1.1pt, fill: accent)[#upper(title)]
})

// --- Masthead. --------------------------------------------------------------
// contacts: array of (icon: str, label: str, url: str or none)
#let cvheader(
  name: "",
  surname: "",
  role: "",
  field: "",
  location: "",
  tagline: "",
  contacts: (),
) = {
  set align(center)
  // Name: match the website masthead — both words semibold, surname in coral.
  block(below: 0pt, {
    text(font: mono, size: 26pt, weight: "semibold", tracking: 0.2pt, fill: ink)[#name ]
    text(font: mono, size: 26pt, weight: "semibold", tracking: 0.2pt, fill: accent)[#surname]
  })
  v(7pt)
  text(font: mono, size: 8.6pt, weight: "medium", tracking: 2.4pt, fill: ink2)[
    #upper(role)#h(8pt)#text(fill: accent)[·]#h(8pt)#upper(field)
  ]
  v(3pt)
  text(font: mono, size: 9.5pt, style: "italic", fill: ink3)[#location]
  v(11pt)
  block(width: 100%, {
    set text(font: mono, size: 9pt, fill: ink2)
    contacts
      .map(c => box({
        icon(c.icon, size: 9.5pt, fill: accent)
        h(4.5pt)
        if c.url != none { link(c.url)[#text(fill: ink2)[#c.label]] } else { text(fill: ink2)[#c.label] }
      }))
      .join(box(inset: (x: 8pt), text(fill: ink3.lighten(15%))[\u{2022}]))
  })
  if tagline != "" {
    v(13pt)
    block(width: 80%, {
      set text(font: mono, size: 10.5pt, style: "italic", fill: ink2)
      set par(leading: 6.6pt, justify: false)
      tagline
    })
  }
  // Clean coral rule closes the masthead (replaces the dot motif).
  v(15pt)
  box(width: 42pt, height: 2.5pt, fill: accent, radius: 1.25pt)
  set align(left)
  v(2pt)
}

// --- The document wrapper, applied as a show rule by typst-show.typ. ---------
#let cv(doc) = {
  set document(title: "Francisco Garre-Frutos — Curriculum Vitae", author: "Francisco Garre-Frutos")
  set page(
    paper: "a4",
    fill: paper,
    margin: (top: 2cm, bottom: 1.7cm, left: 2cm, right: 2cm),
    footer: context {
      set text(font: mono, size: 7.6pt, tracking: 0.5pt, fill: ink3)
      grid(
        columns: (1fr, auto, 1fr),
        align: (left + horizon, center + horizon, right + horizon),
        upper(datetime.today().display("[month repr:long] [year]")),
        upper[Francisco Garre-Frutos #h(4pt)·#h(4pt) Curriculum Vitae],
        [#counter(page).display()],
      )
    },
  )
  set text(font: mono, size: 9.3pt, weight: "regular", fill: ink, lang: "en", hyphenate: false)
  set par(leading: 7.9pt, spacing: 7.9pt, justify: false)
  doc
}
